package com.projectlumen.app.app

import com.projectlumen.app.core.database.entities.TipTemplateEntity
import com.projectlumen.app.core.enums.TemplateBackgroundType

internal object DefaultTipTemplates {
    fun create(nowMillis: Long): List<TipTemplateEntity> {
        return listOf(
            TipTemplateEntity(
                id = 1L,
                name = "Calm teal",
                backgroundValue = "#D4F2F0",
                primaryColor = "#126B66",
                sortOrder = 0,
                createdAt = nowMillis,
                updatedAt = nowMillis,
            ),
            TipTemplateEntity(
                id = 2L,
                name = "Soft sunrise",
                backgroundValue = "#FFE0D4",
                primaryColor = "#B9503E",
                sortOrder = 1,
                createdAt = nowMillis,
                updatedAt = nowMillis,
            ),
            TipTemplateEntity(
                id = 3L,
                name = "Focus indigo",
                backgroundValue = "#E0E3FF",
                primaryColor = "#575EA8",
                sortOrder = 2,
                createdAt = nowMillis,
                updatedAt = nowMillis,
            ),
            TipTemplateEntity(
                id = 4L,
                name = "System colors",
                backgroundType = TemplateBackgroundType.SYSTEM.name,
                backgroundValue = "primaryContainer",
                primaryColor = "primary",
                sortOrder = 3,
                createdAt = nowMillis,
                updatedAt = nowMillis,
            ),
            TipTemplateEntity(
                id = 5L,
                name = "Forest glass",
                backgroundValue = "#DFF7E8",
                primaryColor = "#1F7A4D",
                sortOrder = 4,
                createdAt = nowMillis,
                updatedAt = nowMillis,
            ),
            TipTemplateEntity(
                id = 6L,
                name = "Clear sky",
                backgroundValue = "#DCEBFF",
                primaryColor = "#2563EB",
                isPremium = true,
                sortOrder = 5,
                createdAt = nowMillis,
                updatedAt = nowMillis,
            ),
            TipTemplateEntity(
                id = 7L,
                name = "Rose quartz",
                backgroundValue = "#FFE1EA",
                primaryColor = "#BE3455",
                isPremium = true,
                sortOrder = 6,
                createdAt = nowMillis,
                updatedAt = nowMillis,
            ),
            TipTemplateEntity(
                id = 8L,
                name = "Deep slate",
                backgroundValue = "#E9EEF5",
                primaryColor = "#42526E",
                isPremium = true,
                sortOrder = 7,
                createdAt = nowMillis,
                updatedAt = nowMillis,
            ),
            TipTemplateEntity(
                id = 9L,
                name = "Paper mint",
                backgroundValue = "#F2FFF7",
                primaryColor = "#26734D",
                isPremium = true,
                sortOrder = 8,
                createdAt = nowMillis,
                updatedAt = nowMillis,
            ),
            TipTemplateEntity(
                id = 10L,
                name = "Warm desk",
                backgroundValue = "#FFF4E6",
                primaryColor = "#9A5A16",
                isPremium = true,
                sortOrder = 9,
                createdAt = nowMillis,
                updatedAt = nowMillis,
            ),
            TipTemplateEntity(
                id = 11L,
                name = "Graphite focus",
                backgroundValue = "#F1F2F4",
                primaryColor = "#30343B",
                isPremium = true,
                sortOrder = 10,
                createdAt = nowMillis,
                updatedAt = nowMillis,
            ),
            TipTemplateEntity(
                id = 12L,
                name = "Lotus pause",
                backgroundValue = "#F7E9F2",
                primaryColor = "#8A3F66",
                isPremium = true,
                sortOrder = 11,
                createdAt = nowMillis,
                updatedAt = nowMillis,
            ),
            TipTemplateEntity(
                id = 13L,
                name = "Clinic calm",
                backgroundValue = "#E8F7FA",
                primaryColor = "#1D6F7A",
                isPremium = true,
                sortOrder = 12,
                createdAt = nowMillis,
                updatedAt = nowMillis,
            ),
            TipTemplateEntity(
                id = 14L,
                name = "Night amber",
                backgroundValue = "#2C2A26",
                primaryColor = "#F0B35B",
                isPremium = true,
                sortOrder = 13,
                createdAt = nowMillis,
                updatedAt = nowMillis,
            ),
            TipTemplateEntity(
                id = 15L,
                name = "Reading green",
                backgroundValue = "#EEF7DF",
                primaryColor = "#547325",
                isPremium = true,
                sortOrder = 14,
                createdAt = nowMillis,
                updatedAt = nowMillis,
            ),
        )
    }
}
