package com.projectlumen.app.core.database.entities

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.projectlumen.app.core.enums.AppThemeMode
import com.projectlumen.app.core.enums.PlanTier
import com.projectlumen.app.core.enums.QuietMode
import com.projectlumen.app.core.enums.ReminderAction

@Entity(tableName = "app_settings")
data class AppSettingsEntity(
    @PrimaryKey val id: Int = 1,
    val deviceInstallationId: String = "",
    val languageCode: String = "system",
    val themeMode: String = AppThemeMode.SYSTEM.name,
    val planTier: String = PlanTier.FREE.name,
    val entitlementExpiresAt: Long = 0L,
    val lastEntitlementSyncAt: Long = 0L,
    val reminderEnabled: Boolean = true,
    val warnIntervalMinutes: Int = 20,
    val restDurationSeconds: Int = 20,
    val statsEnabled: Boolean = true,
    val soundEnabled: Boolean = true,
    val vibrationEnabled: Boolean = false,
    val restSoundPath: String = "",
    val restStartSoundEnabled: Boolean = true,
    val restStartSoundPath: String = "",
    val preAlertVolumePercent: Int = 70,
    val restStartVolumePercent: Int = 70,
    val restEndVolumePercent: Int = 70,
    val pomodoroWorkStartVolumePercent: Int = 70,
    val pomodoroWorkEndVolumePercent: Int = 70,
    val preAlertEnabled: Boolean = true,
    val preAlertSeconds: Int = 60,
    val preAlertDefaultAction: String = ReminderAction.START_BREAK.name,
    val preAlertTitle: String = "Eye break soon",
    val preAlertSubtitle: String = "Prepare to rest",
    val preAlertMessage: String = "A break will start shortly.",
    val preAlertIconPath: String = "",
    val preAlertSoundEnabled: Boolean = true,
    val askBeforeBreak: Boolean = true,
    val disableSkip: Boolean = false,
    val timeoutAutoBreak: Boolean = false,
    val pomodoroEnabled: Boolean = true,
    val pomodoroWorkMinutes: Int = 25,
    val pomodoroShortBreakMinutes: Int = 5,
    val pomodoroLongBreakMinutes: Int = 15,
    val pomodoroInteractiveMode: Boolean = false,
    val pomodoroWorkStartSoundEnabled: Boolean = true,
    val pomodoroWorkEndSoundEnabled: Boolean = true,
    val pomodoroWorkStartSoundPath: String = "",
    val pomodoroWorkEndSoundPath: String = "",
    val activeTipTemplateId: Long = 1L,
    val statsWorkImagePath: String = "",
    val statsRestImagePath: String = "",
    val statsSkipImagePath: String = "",
    val useAutoDarkWindow: Boolean = false,
    val autoDarkStartMinute: Int = 1080,
    val autoDarkEndMinute: Int = 360,
    val quietHoursEnabled: Boolean = false,
    val quietStartMinute: Int = 1320,
    val quietEndMinute: Int = 420,
    val quietMode: String = QuietMode.PAUSE_TIMER.name,
    val notificationEnabled: Boolean = true,
    val keepAliveEnabled: Boolean = true,
    val proximityMonitoringEnabled: Boolean = false,
    val proximityBaselineEyeDistancePx: Float = 0f,
    val proximityBaselineFaceWidthPercent: Int = 0,
    val proximityDistanceMultiplierPercent: Int = 130,
    val proximityCheckIntervalMinutes: Int = 3,
    val proximityCaptureSeconds: Int = 2,
    val proximityFaceThresholdPercent: Int = 38,
    val proximityAlertCooldownSeconds: Int = 120,
    val blinkMonitoringEnabled: Boolean = false,
    val blinkNoBlinkThresholdSeconds: Int = 10,
    val blinkAlertCooldownSeconds: Int = 60,
    val ambientLightMonitoringEnabled: Boolean = false,
    val ambientLightLowLuxThreshold: Int = 10,
    val autoBrightnessEnabled: Boolean = false,
    val autoBrightnessMinPercent: Int = 35,
    val autoBrightnessMaxPercent: Int = 85,
    val globalOverlayEnabled: Boolean = true,
    val overlayRestDurationSeconds: Int = 20,
    val overlayStrictDistancePercent: Int = 160,
    val developerModeEnabled: Boolean = false,
    val developerDebugOverlayEnabled: Boolean = false,
    val developerDebugPreviewEnabled: Boolean = false,
    val developerTickIntervalSeconds: Int = 180,
    val developerTimeTriggerEnabled: Boolean = true,
    val developerUnlockTriggerEnabled: Boolean = true,
    val developerStillnessTriggerEnabled: Boolean = true,
    val developerShakeSuppressionEnabled: Boolean = true,
    val autoUpdateCheckEnabled: Boolean = true,
    val updatedAt: Long = System.currentTimeMillis(),
)
