package com.projectlumen.app.core.api

import org.json.JSONArray
import org.json.JSONObject

internal fun RemoteTelemetryUpload.toJson(): JSONObject = JSONObject()
    .put("deviceInstallationId", deviceInstallationId)
    .put("sourceApp", sourceApp)
    .put("recordedAt", recordedAt)
    .putNullable("dailyHealth", dailyHealth?.toJson())
    .put("environmentContext", JSONArray(environmentContext.map { it.toJson() }))
    .put("deviceProfile", deviceProfile.toJson())
    .putNullable("calibrationAnchor", calibrationAnchor?.toJson())
    .putNullable("aiPerformance", aiPerformance?.toJson())
    .putNullable("developerDebug", developerDebug?.toJson())
    .putNullable("deviceDiagnostics", deviceDiagnostics?.toJson())
    .putNullable("pomodoroProductivity", pomodoroProductivity?.toJson())
    .putNullable("userConfiguration", userConfiguration?.toJson())

internal fun JSONObject.toTelemetryUploadResult(): RemoteTelemetryUploadResult = RemoteTelemetryUploadResult(
    accepted = optBoolean("accepted"),
    id = optString("id"),
    receivedAt = optLong("receivedAt"),
)

private fun DailyEyeHealthTelemetry.toJson(): JSONObject = JSONObject()
    .put("statDate", statDate)
    .put("totalScreenSeconds", totalScreenSeconds)
    .put("restSeconds", restSeconds)
    .put("continuousOverTwentyCount", continuousOverTwentyCount)
    .put("maxContinuousWorkSeconds", maxContinuousWorkSeconds)
    .put("distanceViolationCount", distanceViolationCount)
    .put("distanceCloseSeconds", distanceCloseSeconds)
    .put("lowLightWarningCount", lowLightWarningCount)
    .put("distanceViolations", JSONArray(distanceViolations.map { it.toJson() }))
    .put("blinkMetrics", blinkMetrics.toJson())
    .put("restCompliance", restCompliance.toJson())

private fun PomodoroProductivityTelemetry.toJson(): JSONObject = JSONObject()
    .put("statDate", statDate)
    .put("completedTomatoCount", completedTomatoCount)
    .put("restartCount", restartCount)
    .put("completedFocusSessions", completedFocusSessions)
    .put("totalFocusSeconds", totalFocusSeconds)
    .put("totalBreakSeconds", totalBreakSeconds)

private fun DistanceViolationTelemetry.toJson(): JSONObject = JSONObject()
    .put("recordedAt", recordedAt)
    .put("distanceFactor", distanceFactor)
    .put("ratioPercent", ratioPercent)
    .put("closeSeconds", closeSeconds)

private fun BlinkMetricsTelemetry.toJson(): JSONObject = JSONObject()
    .putNullable("averageBlinksPerMinute", averageBlinksPerMinute)
    .put("eyeDryWarningCount", eyeDryWarningCount)
    .put("severeEyeDryRisk", severeEyeDryRisk)
    .putNullable("lastEyeOpenProbabilityPercent", lastEyeOpenProbabilityPercent)

private fun RestComplianceTelemetry.toJson(): JSONObject = JSONObject()
    .put("completedBreakCount", completedBreakCount)
    .put("skippedBreakCount", skippedBreakCount)
    .put("complianceRatePercent", complianceRatePercent)

private fun EnvironmentContextTelemetry.toJson(): JSONObject = JSONObject()
    .put("recordedAt", recordedAt)
    .put("luxLevel", luxLevel)
    .put("poseStatus", poseStatus)
    .put("scenarioStatus", scenarioStatus)

private fun DeviceProfileTelemetry.toJson(): JSONObject = JSONObject()
    .put("manufacturer", manufacturer)
    .put("model", model)
    .put("androidRelease", androidRelease)
    .put("androidSdk", androidSdk)
    .put("frontCameraResolution", frontCameraResolution)
    .put("appVersionName", appVersionName)
    .put("appVersionCode", appVersionCode)

private fun DeviceDiagnosticsTelemetry.toJson(): JSONObject = JSONObject()
    .put("consentActiveAt", consentActiveAt)
    .put("collectedAt", collectedAt)
    .put("collectionSource", collectionSource)
    .put("shizukuReady", shizukuReady)
    .put("shizukuServerVersion", shizukuServerVersion)
    .put("shizukuServerUid", shizukuServerUid)
    .put("userAppCount", userAppCount)
    .put("userAppsTruncated", userAppsTruncated)
    .put("userApps", JSONArray(userApps.map { it.toJson() }))

private fun InstalledAppTelemetry.toJson(): JSONObject = JSONObject()
    .put("packageName", packageName)
    .put("installerPackageName", installerPackageName)
    .putNullable("versionCode", versionCode)
    .putNullable("uid", uid)

private fun CalibrationAnchorTelemetry.toJson(): JSONObject = JSONObject()
    .put("standardDistanceCm", standardDistanceCm)
    .put("baseFaceWidthPercent", baseFaceWidthPercent)
    .put("baseEyeDistancePx", baseEyeDistancePx)

private fun AiPerformanceTelemetry.toJson(): JSONObject = JSONObject()
    .put("averageFaceDetectionMs", averageFaceDetectionMs)
    .put("cameraLatencyMs", cameraLatencyMs)
    .put("backgroundKillCount", backgroundKillCount)

private fun DeveloperDebugTelemetry.toJson(): JSONObject = JSONObject()
    .putNullable("sensorDisturbance", sensorDisturbance?.toJson())
    .put("crashLogs", JSONArray(crashLogs.map { it.toJson() }))
    .put("apiTraces", JSONArray(apiTraces.map { it.toJson() }))

private fun ApiTraceTelemetry.toJson(): JSONObject = JSONObject()
    .put("startedAt", startedAt)
    .put("method", method)
    .put("path", path)
    .put("signed", signed)
    .put("integrityRequested", integrityRequested)
    .put("authorizationAttached", authorizationAttached)
    .putNullable("statusCode", statusCode)
    .put("durationMillis", durationMillis)
    .put("errorType", errorType)
    .put("errorMessage", errorMessage)

private fun SensorDisturbanceTelemetry.toJson(): JSONObject = JSONObject()
    .put("pitchDegrees", pitchDegrees)
    .put("rollDegrees", rollDegrees)
    .put("yawDegrees", yawDegrees)
    .put("accelerationMagnitude", accelerationMagnitude)

private fun CrashLogTelemetry.toJson(): JSONObject = JSONObject()
    .put("crashedAt", crashedAt)
    .put("exceptionType", exceptionType)
    .put("rootCause", rootCause)
    .put("stackTraceLines", JSONArray(stackTraceLines))

private fun UserConfigurationTelemetry.toJson(): JSONObject = JSONObject()
    .putNullable("dailyGoal", dailyGoal?.toJson())
    .putNullable("audioFeedback", audioFeedback?.toJson())
    .put("reminderPlans", JSONArray(reminderPlans.map { it.toJson() }))
    .put("tipTemplates", JSONArray(tipTemplates.map { it.toJson() }))

private fun AudioFeedbackTelemetry.toJson(): JSONObject = JSONObject()
    .put("soundEnabled", soundEnabled)
    .put("vibrationEnabled", vibrationEnabled)
    .put("preAlertSoundEnabled", preAlertSoundEnabled)
    .put("restStartSoundEnabled", restStartSoundEnabled)
    .put("pomodoroWorkStartSoundEnabled", pomodoroWorkStartSoundEnabled)
    .put("pomodoroWorkEndSoundEnabled", pomodoroWorkEndSoundEnabled)
    .put("preAlertVolumePercent", preAlertVolumePercent)
    .put("restStartVolumePercent", restStartVolumePercent)
    .put("restEndVolumePercent", restEndVolumePercent)
    .put("pomodoroWorkStartVolumePercent", pomodoroWorkStartVolumePercent)
    .put("pomodoroWorkEndVolumePercent", pomodoroWorkEndVolumePercent)

private fun DailyGoalTelemetry.toJson(): JSONObject = JSONObject()
    .put("restBreakGoal", restBreakGoal)
    .put("maxContinuousWorkMinutes", maxContinuousWorkMinutes)
    .put("pomodoroGoal", pomodoroGoal)
    .put("weeklyActiveDaysGoal", weeklyActiveDaysGoal)
    .put("updatedAt", updatedAt)

private fun ReminderPlanTelemetry.toJson(): JSONObject = JSONObject()
    .put("id", id)
    .put("enabled", enabled)
    .put("warnIntervalMinutes", warnIntervalMinutes)
    .put("restDurationSeconds", restDurationSeconds)
    .put("quietHoursEnabled", quietHoursEnabled)
    .put("quietMode", quietMode)
    .put("sortOrder", sortOrder)
    .put("updatedAt", updatedAt)

private fun TipTemplateTelemetry.toJson(): JSONObject = JSONObject()
    .put("id", id)
    .put("isBuiltin", isBuiltin)
    .put("backgroundType", backgroundType)
    .put("hasImage", hasImage)
    .put("showSkipButton", showSkipButton)
    .put("isPremium", isPremium)
    .put("hasRemoteId", hasRemoteId)
    .put("countdownStyle", countdownStyle)
    .put("sortOrder", sortOrder)
    .put("updatedAt", updatedAt)

private fun JSONObject.putNullable(name: String, value: Any?): JSONObject {
    if (value == null) {
        put(name, JSONObject.NULL)
    } else {
        put(name, value)
    }
    return this
}
